// Code generated by ent, DO NOT EDIT.

package ent

import (
	"text2manim-demo-server/internal/domain/ent/generation"
	"text2manim-demo-server/internal/domain/ent/schema"
	"time"

	"github.com/google/uuid"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	generationFields := schema.Generation{}.Fields()
	_ = generationFields
	// generationDescCreatedAt is the schema descriptor for created_at field.
	generationDescCreatedAt := generationFields[8].Descriptor()
	// generation.DefaultCreatedAt holds the default value on creation for the created_at field.
	generation.DefaultCreatedAt = generationDescCreatedAt.Default.(func() time.Time)
	// generationDescUpdatedAt is the schema descriptor for updated_at field.
	generationDescUpdatedAt := generationFields[9].Descriptor()
	// generation.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	generation.DefaultUpdatedAt = generationDescUpdatedAt.Default.(func() time.Time)
	// generation.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	generation.UpdateDefaultUpdatedAt = generationDescUpdatedAt.UpdateDefault.(func() time.Time)
	// generationDescID is the schema descriptor for id field.
	generationDescID := generationFields[0].Descriptor()
	// generation.DefaultID holds the default value on creation for the id field.
	generation.DefaultID = generationDescID.Default.(func() uuid.UUID)
}
